feat: add ReadOption.ReadTime to support timestamp reads.
googleapis/java-datastore pull request #712
Opened 2022-04-18 18:33 UTC by yixiaoshen

Thank you for opening a Pull Request! Before submitting your PR, there are a few things you can do to make sure it goes smoothly:
- [ ] Make sure to open an issue as a [bug/issue](https://github.com/googleapis/java-datastore/issues/new/choose) before writing your code!  That way we can discuss the change, evaluate designs, and agree on the general idea
- [ ] Ensure the tests and linter pass
- [ ] Code coverage does not decrease (if any source code was changed)
- [ ] Appropriate docs were updated (if necessary)

Fixes #<issue_number_goes_here> ☕️

If you write sample code, please follow the [samples format](
https://github.com/GoogleCloudPlatform/java-docs-samples/blob/main/SAMPLE_FORMAT.md).

2022-04-21 17:48 UTC, kolea2 reviewed
looks good, can we also add an integration test?

2022-05-12 18:07 UTC, kolea2 requested changes

2022-05-12 18:07 UTC, kolea2 commented on google-cloud-datastore/src/main/java/com/google/cloud/datastore/ReadOption.java
> +  public static ReadTime readTime(Timestamp time) {
please add `@BetaApi`

2022-05-19 19:15 UTC, yixiaoshen commented on google-cloud-datastore/src/main/java/com/google/cloud/datastore/ReadOption.java
> +  public static ReadTime readTime(Timestamp time) {
done

2022-05-23 18:06 UTC, kolea2 approved these changes

2022-05-23 19:06 UTC, merged